# Generated by Django 5.2.4 on 2025-07-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('processor', models.CharField(max_length=100)),
                ('cpu_cores', models.IntegerField()),
                ('cpu_clock_speed', models.FloatField()),
                ('battery_life', models.CharField(max_length=10)),
                ('ram', models.IntegerField()),
                ('storage', models.CharField(max_length=50)),
                ('gpu', models.CharField(max_length=100)),
                ('gpu_score', models.IntegerField()),
                ('screen_resolution', models.CharField(max_length=50)),
                ('refresh_rate', models.IntegerField()),
                ('display', models.CharField(max_length=100)),
                ('keyboard', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('weight', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
